100-hours-a-week/7-team-kono-be

- .github/workflows/release.yml
> fix: replace dependencies

- src/main/java/org/secretjuju/kono/controller/CoinController.java
- src/main/java/org/secretjuju/kono/repository/CoinInfoRepository.java
- src/main/java/org/secretjuju/kono/service/CoinService.java
코인 전체 목록 조회 API 
- Resolves #46
/api/v1/coins GET 코인 전체 목록을 조회하는 API 구현 완료
1. 200번대 postman test 성공 /api/v1/coins
> feat: 코인 목록 전체 조회

- src/main/java/org/secretjuju/kono/controller/UserController.java
- src/main/java/org/secretjuju/kono/service/CoinFavoriteService.java
특정 관심코인 여부 확인 API 추가
GET  /api/v1/users/favorites/{ticker} 특정 관심코인 여부 확인 API 추가 완료
GET  /api/v1/users/favorites/{ticker}
> Feat: 특정 관심 코인 확인

- src/main/java/org/secretjuju/kono/config/SecurityConfig.java
- src/main/java/org/secretjuju/kono/dto/response/TransactionHistoryResponseDto.java
- src/main/java/org/secretjuju/kono/dto/response/UserResponseDto.java
- src/main/java/org/secretjuju/kono/entity/CoinTransaction.java
- src/main/java/org/secretjuju/kono/entity/DailyRanking.java
- src/main/java/org/secretjuju/kono/entity/TotalRanking.java
- src/main/java/org/secretjuju/kono/entity/User.java
- src/main/java/org/secretjuju/kono/service/CoinService.java
- src/main/java/org/secretjuju/kono/service/OAuth2UserService.java
코인 거래시 holding_price 값 현재가 -> 나의 코인 매수금액
refactor: coin-sell-buy hoding_price
> refactor: feat/coin trade

- src/main/java/org/secretjuju/kono/dto/response/TotalRankingResponseDto.java
- src/main/java/org/secretjuju/kono/entity/TotalRanking.java
- src/main/java/org/secretjuju/kono/service/RankingService.java
- 수정 전 : 전체랭킹 현재 총 자산으로 반환됨.
- 수정 후 : 전체랭킹 수익금으로 반환됨. (수익금 = 현재 총 자산 - 1천만원)
- Resolves #58 
1. 🛠️ [변경 내용 1] 전체랭킹 entity 수정 : profit을 구하는 함수 추가(getProfit), 초기자산(1천만원) 변수 선언
2. 📝 [변경 내용 2] 전체랭킹 응답 dto 수정 : 현재총자산 -> profit 필드로 수정
3. 🔧 [변경 내용 3] 랭킹 service 수정 : 전체 랭킹 함수 - getProfit으로 수익금 구해서 리턴하도록 수정
1. ✅ [테스트 1]
2. 🖥️ [테스트 2]
3. 📱 [테스트 3]
> fix: 전체랭킹 수익금으로 반환

- src/main/java/org/secretjuju/kono/config/RankingScheduler.java
- src/main/java/org/secretjuju/kono/config/RestTemplateConfig.java
- src/main/java/org/secretjuju/kono/config/SecurityConfig.java
- src/main/java/org/secretjuju/kono/service/CoinPriceService.java
- src/main/java/org/secretjuju/kono/service/RankingService.java
429 TooManyRequests 에러 해결
- Resolves #60 
1. 🛠️ [변경 내용 1] 현재가 불러오는 방식 : 티커마다 불러옴 -> 최대 100개씩 불러옴 
2. 📝 [변경 내용 2] 현재가 저장방식 : 한번의 요청에 100개의 ticker 현재가를 요청하여 메모리에 저장함. 
3. 🔧 [변경 내용 3]
1. ✅ [테스트 1]
2. 🖥️ [테스트 2]
3. 📱 [테스트 3]
> feat: too many requests error 해결

- src/main/java/org/secretjuju/kono/service/CoinService.java
잔여 코인 남은것 +2원으로 처리
- Resolves #70
> fix: delete-remain-coin

- src/main/java/org/secretjuju/kono/entity/DailyRanking.java
- src/main/java/org/secretjuju/kono/entity/TotalRanking.java
- 기존 버그 : 처음 가입한 사용자가 거래를 한 이후에도 일간랭킹이 0.00%인 에러
- 에러 해결 완료!
- Resolves #72 
- 일간랭킹 계산법 = (오늘 총 자산 - 어제 총 자산) / 어제 총 자산
- 원인 분석 : 어제 총 자산을 0으로 초기화 했었어서 일간랭킹이 0.00%로 나왔었음
1. 🛠️ [변경 내용 1] 처음 가입한 사람의 어제 총자산을 0으로 초기화
2. 📝 [변경 내용 2]
3. 🔧 [변경 내용 3]
1. ✅ [테스트 1]
2. 🖥️ [테스트 2]
3. 📱 [테스트 3]
> fix: new user daily ranking

- src/main/java/org/secretjuju/kono/config/SecurityConfig.java
- src/main/java/org/secretjuju/kono/service/CoinService.java
작은 단위로 남는 코인 제거
- Resolves #70
> fix: delete remain coin

- build.gradle
- src/main/java/org/secretjuju/kono/config/SecurityConfig.java
- src/main/java/org/secretjuju/kono/controller/UserController.java
- src/main/java/org/secretjuju/kono/dto/response/ErrorResponse.java
- src/main/java/org/secretjuju/kono/service/UserService.java
닉네임 변경 시. 유효성 검사 예외 처리에 대한 부분 수정 
#104 #120
1. 🛠️  자신의 닉네임이여도 변경 요청 시 409 요청 보내게 수정
2. 📝 유효성 검사이후에 대한 오류 메세지 구체적으로 수정 
3. 🔧 에러 메세지를 프론트에 전달하도록 수정 
1. ✅  400: 유효성 검사에 따른 구체적인 메세지 확인
2. 🖥️  409: 닉네임 중복에 대한 메세지 확인
> fix: exception-nickname

- src/main/java/org/secretjuju/kono/dto/response/DailyRankingResponseDto.java
- src/main/java/org/secretjuju/kono/dto/response/TotalRankingResponseDto.java
- src/main/java/org/secretjuju/kono/service/RankingService.java
랭킹 API 응답할때, 랭킹의 마지막 업데이트 시간(`updatedAt`)을 함께 보내도록 추가함 
- FE 109이슈 해결완료
- https://github.com/100-hours-a-week/7-team-kono-fe/issues/109
1. 🛠️ [변경 내용 1] 랭킹 DTO에 `updatedAt` 추가
2. 📝 [변경 내용 2] 랭킹 API 응답에 `updatedAt` 추가
3. 🔧 [변경 내용 3]
1. ✅ [테스트 1]
2. 🖥️ [테스트 2]
3. 📱 [테스트 3]
> feat: get ranking last updated

- src/main/java/org/secretjuju/kono/config/SecurityConfig.java
- src/main/java/org/secretjuju/kono/service/CoinService.java
- src/main/resources/application.yml
> feat: set env

- .github/workflows/backend.yml
> fix: backend.yml

- build.gradle
- src/main/java/org/secretjuju/kono/config/RateLimitPolicy.java
- src/main/java/org/secretjuju/kono/config/SecurityConfig.java
- src/main/java/org/secretjuju/kono/config/WebMvcConfig.java
- src/main/java/org/secretjuju/kono/interceptor/RateLimitInterceptor.java
- src/main/java/org/secretjuju/kono/service/RateLimitService.java
- src/main/resources/application.yml
- src/test/java/org/secretjuju/kono/service/RateLimitServiceTest.java
- src/test/resources/application-test.yml
API rate Limit 설정
abuse 방지, API 안정성 보장, 사용량 제어 위해  API rate Limit 설정
- 요청수를 제한하는 테스트코드 실행 후. 요청제한의 테스트 성공
> feat: API rate Limit 설정

- .github/workflows/backend.yml
> fix backend.yml

- src/main/java/org/secretjuju/kono/config/SecurityConfig.java
- src/main/java/org/secretjuju/kono/service/S3Service.java
- src/main/resources/application.yml
> feat: check-env

- src/main/java/org/secretjuju/kono/service/S3Service.java
fix: profile-upload-uri구분자 추가
이미지 경로를 추가하면서 profile-upload-uri구분자 추가
- [] 🔄 코드가 정상적으로 컴파일되는지 확인했습니다.
> fix: profile-upload-uri구분자 추가

- src/main/java/org/secretjuju/kono/service/S3Service.java
> fix: profile-upload-uri 이미지 경로 제거

- .github/workflows/deploy.yml
> ci: add deploy.yml

- src/main/java/org/secretjuju/kono/config/RankingScheduler.java
- src/main/java/org/secretjuju/kono/config/SecurityConfig.java
- src/main/resources/application.yml
🧑‍💻 PR Type
📌 Description
자동 로그인을 위한 prompt 비활성화
> feat: prompt 비활성화
